///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TeqtRano
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AgrandirNaviguateur recording.
    /// </summary>
    [TestModule("abb87c45-7458-47ce-9be2-f8f403e7c75f", ModuleType.Recording, 1)]
    public partial class AgrandirNaviguateur : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TeqtRanoRepository repository.
        /// </summary>
        public static TeqtRanoRepository repo = TeqtRanoRepository.Instance;

        static AgrandirNaviguateur instance = new AgrandirNaviguateur();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AgrandirNaviguateur()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AgrandirNaviguateur Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MessagerieViaducBienvenueSurMessa1.PageTabList' at 474;7.", repo.MessagerieViaducBienvenueSurMessa1.PageTabListInfo, new RecordItemIndex(0));
            repo.MessagerieViaducBienvenueSurMessa1.PageTabList.DoubleClick("474;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
