///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TeqtRano
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SaisieLoginUser recording.
    /// </summary>
    [TestModule("7ba4c0ec-8dd7-48aa-bee1-bedfeccba616", ModuleType.Recording, 1)]
    public partial class SaisieLoginUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TeqtRanoRepository repository.
        /// </summary>
        public static TeqtRanoRepository repo = TeqtRanoRepository.Instance;

        static SaisieLoginUser instance = new SaisieLoginUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SaisieLoginUser()
        {
            Login = "adiagne";
            DebutLoginUserName = "adiagne";
            FinLoginUserName = "{LControlKey down}{RMenu down}{D0}{LControlKey up}{RMenu up}{LControlKey up}zenity{Decimal}fr";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SaisieLoginUser Instance
        {
            get { return instance; }
        }

#region Variables

        string _Login;

        /// <summary>
        /// Gets or sets the value of variable Login.
        /// </summary>
        [TestVariable("806e886b-6f8a-437d-9de4-512cefd8d4fb")]
        public string Login
        {
            get { return _Login; }
            set { _Login = value; }
        }

        string _DebutLoginUserName;

        /// <summary>
        /// Gets or sets the value of variable DebutLoginUserName.
        /// </summary>
        [TestVariable("e05f97af-13e8-4e78-86ea-8442f1150c68")]
        public string DebutLoginUserName
        {
            get { return _DebutLoginUserName; }
            set { _DebutLoginUserName = value; }
        }

        string _FinLoginUserName;

        /// <summary>
        /// Gets or sets the value of variable FinLoginUserName.
        /// </summary>
        [TestVariable("1f114b32-456c-4382-afa0-d318da00cc59")]
        public string FinLoginUserName
        {
            get { return _FinLoginUserName; }
            set { _FinLoginUserName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa.Rcmloginuser' at 136;12.", repo.MessagerieViaducBienvenueSurMessa.RcmloginuserInfo, new RecordItemIndex(0));
            repo.MessagerieViaducBienvenueSurMessa.Rcmloginuser.Click("136;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DebutLoginUserName' with focus on 'MessagerieViaducBienvenueSurMessa1'.", repo.MessagerieViaducBienvenueSurMessa1.SelfInfo, new RecordItemIndex(1));
            repo.MessagerieViaducBienvenueSurMessa1.Self.PressKeys(DebutLoginUserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FinLoginUserName' with focus on 'MessagerieViaducBienvenueSurMessa1'.", repo.MessagerieViaducBienvenueSurMessa1.SelfInfo, new RecordItemIndex(2));
            repo.MessagerieViaducBienvenueSurMessa1.Self.PressKeys(FinLoginUserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa.Welcome' at 447;145.", repo.MessagerieViaducBienvenueSurMessa.WelcomeInfo, new RecordItemIndex(3));
            repo.MessagerieViaducBienvenueSurMessa.Welcome.Click("447;145");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.MessagerieViaducBienvenueSurMessa' at 44;6.", repo.Explorer.MessagerieViaducBienvenueSurMessaInfo, new RecordItemIndex(4));
            //repo.Explorer.MessagerieViaducBienvenueSurMessa.Click("44;6");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa1.Element192300696' at 380;278.", repo.MessagerieViaducBienvenueSurMessa1.Element192300696Info, new RecordItemIndex(5));
            //repo.MessagerieViaducBienvenueSurMessa1.Element192300696.Click("380;278");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
