///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TeqtRano
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SaisieLoginPassword recording.
    /// </summary>
    [TestModule("330285dd-677b-44a5-ae90-c9f9033c69e6", ModuleType.Recording, 1)]
    public partial class SaisieLoginPassword : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TeqtRanoRepository repository.
        /// </summary>
        public static TeqtRanoRepository repo = TeqtRanoRepository.Instance;

        static SaisieLoginPassword instance = new SaisieLoginPassword();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SaisieLoginPassword()
        {
            Password = "zenity{NumPad0}{NumPad1}{NumPad0}{NumPad7}{NumPad1}{NumPad4}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SaisieLoginPassword Instance
        {
            get { return instance; }
        }

#region Variables

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("fce76b5f-31dd-412e-9a05-927f96a425eb")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa.Rcmloginpwd' at 120;7.", repo.MessagerieViaducBienvenueSurMessa.RcmloginpwdInfo, new RecordItemIndex(0));
            repo.MessagerieViaducBienvenueSurMessa.Rcmloginpwd.Click("120;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'MessagerieViaducBienvenueSurMessa.Rcmloginpwd'.", repo.MessagerieViaducBienvenueSurMessa.RcmloginpwdInfo, new RecordItemIndex(1));
            repo.MessagerieViaducBienvenueSurMessa.Rcmloginpwd.PressKeys(Password);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'zenity{NumPad0}{NumPad1}{NumPad0}{NumPad7}{NumPad1}{NumPad4}' with focus on 'MessagerieViaducBienvenueSurMessa.Rcmloginpwd'.", repo.MessagerieViaducBienvenueSurMessa.RcmloginpwdInfo, new RecordItemIndex(2));
            //repo.MessagerieViaducBienvenueSurMessa.Rcmloginpwd.PressKeys("zenity{NumPad0}{NumPad1}{NumPad0}{NumPad7}{NumPad1}{NumPad4}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.MessagerieViaducBienvenueSurMessa' at 57;21.", repo.Explorer.MessagerieViaducBienvenueSurMessaInfo, new RecordItemIndex(3));
            //repo.Explorer.MessagerieViaducBienvenueSurMessa.Click("57;21");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa1.Element192300696' at 341;323.", repo.MessagerieViaducBienvenueSurMessa1.Element192300696Info, new RecordItemIndex(4));
            //repo.MessagerieViaducBienvenueSurMessa1.Element192300696.Click("341;323");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Password' with focus on 'MessagerieViaducBienvenueSurMessa1'.", repo.MessagerieViaducBienvenueSurMessa1.SelfInfo, new RecordItemIndex(5));
            //repo.MessagerieViaducBienvenueSurMessa1.Self.PressKeys(Password);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
