///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TeqtRano
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TeqtRanoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    [RepositoryFolder("3210af4d-4347-4f81-aa07-317fc26e8e22")]
    public partial class TeqtRanoRepository : RepoGenBaseFolder
    {
        static TeqtRanoRepository instance = new TeqtRanoRepository();
        TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessaAppFolder _messagerieviaducbienvenuesurmessa;
        TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessa1AppFolder _messagerieviaducbienvenuesurmessa1;
        TeqtRanoRepositoryFolders.ExplorerAppFolder _explorer;
        TeqtRanoRepositoryFolders.MessagerieViaducMessagesRecusGoAppFolder _messagerieviaducmessagesrecusgo;

        /// <summary>
        /// Gets the singleton class instance representing the TeqtRanoRepository element repository.
        /// </summary>
        [RepositoryFolder("3210af4d-4347-4f81-aa07-317fc26e8e22")]
        public static TeqtRanoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TeqtRanoRepository() 
            : base("TeqtRanoRepository", "/", null, 0, false, "3210af4d-4347-4f81-aa07-317fc26e8e22", ".\\RepositoryImages\\TeqtRanoRepository3210af4d.rximgres")
        {
            _messagerieviaducbienvenuesurmessa = new TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessaAppFolder(this);
            _messagerieviaducbienvenuesurmessa1 = new TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessa1AppFolder(this);
            _explorer = new TeqtRanoRepositoryFolders.ExplorerAppFolder(this);
            _messagerieviaducmessagesrecusgo = new TeqtRanoRepositoryFolders.MessagerieViaducMessagesRecusGoAppFolder(this);
        }

#region Variables

        string _welcome = "welcome";

        /// <summary>
        /// Gets or sets the value of variable welcome.
        /// </summary>
        [TestVariable("0a0b592e-7b24-49f8-8544-cdb6cee029aa")]
        public string welcome
        {
            get { return _welcome; }
            set { _welcome = value; }
        }

        string _PageMail = "Google Chrome";

        /// <summary>
        /// Gets or sets the value of variable PageMail.
        /// </summary>
        [TestVariable("0896eab2-cc72-4288-97ec-711d7b375f1c")]
        public string PageMail
        {
            get { return _PageMail; }
            set { _PageMail = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3210af4d-4347-4f81-aa07-317fc26e8e22")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MessagerieViaducBienvenueSurMessa folder.
        /// </summary>
        [RepositoryFolder("140df5e1-1ee4-45df-9f72-217ae940cd2d")]
        public virtual TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessaAppFolder MessagerieViaducBienvenueSurMessa
        {
            get { return _messagerieviaducbienvenuesurmessa; }
        }

        /// <summary>
        /// The MessagerieViaducBienvenueSurMessa1 folder.
        /// </summary>
        [RepositoryFolder("2e4806e2-656f-43af-acf3-27b971ed5819")]
        public virtual TeqtRanoRepositoryFolders.MessagerieViaducBienvenueSurMessa1AppFolder MessagerieViaducBienvenueSurMessa1
        {
            get { return _messagerieviaducbienvenuesurmessa1; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("1db093ea-491a-4527-a793-62d73858c325")]
        public virtual TeqtRanoRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The MessagerieViaducMessagesRecusGo folder.
        /// </summary>
        [RepositoryFolder("803053fd-cd02-440e-9b53-4ea3d95b4d14")]
        public virtual TeqtRanoRepositoryFolders.MessagerieViaducMessagesRecusGoAppFolder MessagerieViaducMessagesRecusGo
        {
            get { return _messagerieviaducmessagesrecusgo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
    public partial class TeqtRanoRepositoryFolders
    {
        /// <summary>
        /// The MessagerieViaducBienvenueSurMessaAppFolder folder.
        /// </summary>
        [RepositoryFolder("140df5e1-1ee4-45df-9f72-217ae940cd2d")]
        public partial class MessagerieViaducBienvenueSurMessaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rcmloginpwdInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _rcmloginuserInfo;
            RepoItemInfo _welcomeInfo;
            RepoItemInfo _minmodetoggleInfo;
            RepoItemInfo _adiagneatzenityfrInfo;
            RepoItemInfo _rcmbtn101Info;

            /// <summary>
            /// Creates a new MessagerieViaducBienvenueSurMessa  folder.
            /// </summary>
            public MessagerieViaducBienvenueSurMessaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessagerieViaducBienvenueSurMessa", "/dom[@domain='webmail.zenity.fr']", parentFolder, 30000, null, false, "140df5e1-1ee4-45df-9f72-217ae940cd2d", "")
            {
                _rcmloginpwdInfo = new RepoItemInfo(this, "Rcmloginpwd", ".//input[#'rcmloginpwd']", 30000, null, "0634ecf4-2b7d-468d-8979-9d24e73c243b");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'login-form']/?/?/form[@name='form']/?/?/input[@type='submit']", 30000, null, "2c13f5b1-ce2b-4858-9bed-3bf45a9ca65b");
                _rcmloginuserInfo = new RepoItemInfo(this, "Rcmloginuser", ".//input[#'rcmloginuser']", 30000, null, "3064f1ad-4a1f-467f-8b55-6e2843001075");
                _welcomeInfo = new RepoItemInfo(this, "Welcome", ".//div[#'login-form']/div[@class='welcome']", 30000, null, "925a003a-60ec-481d-803d-074fe0faeffc");
                _minmodetoggleInfo = new RepoItemInfo(this, "Minmodetoggle", ".//div[#'taskbar']/span", 30000, null, "716da320-4020-4115-9937-a68be52b36bf");
                _adiagneatzenityfrInfo = new RepoItemInfo(this, "AdiagneAtzenityFr", ".//div[#'topline']/?/?/span[@innertext='adiagne@zenity.fr']", 30000, null, "c9e65b8b-f806-46c4-af3c-19b296961954");
                _rcmbtn101Info = new RepoItemInfo(this, "Rcmbtn101", ".//a[#'rcmbtn101']", 30000, null, "b904b428-fe46-4fc7-807b-7b84c94065e6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("140df5e1-1ee4-45df-9f72-217ae940cd2d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("140df5e1-1ee4-45df-9f72-217ae940cd2d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Rcmloginpwd item.
            /// </summary>
            [RepositoryItem("0634ecf4-2b7d-468d-8979-9d24e73c243b")]
            public virtual Ranorex.InputTag Rcmloginpwd
            {
                get
                {
                    return _rcmloginpwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Rcmloginpwd item info.
            /// </summary>
            [RepositoryItemInfo("0634ecf4-2b7d-468d-8979-9d24e73c243b")]
            public virtual RepoItemInfo RcmloginpwdInfo
            {
                get
                {
                    return _rcmloginpwdInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("2c13f5b1-ce2b-4858-9bed-3bf45a9ca65b")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("2c13f5b1-ce2b-4858-9bed-3bf45a9ca65b")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Rcmloginuser item.
            /// </summary>
            [RepositoryItem("3064f1ad-4a1f-467f-8b55-6e2843001075")]
            public virtual Ranorex.InputTag Rcmloginuser
            {
                get
                {
                    return _rcmloginuserInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Rcmloginuser item info.
            /// </summary>
            [RepositoryItemInfo("3064f1ad-4a1f-467f-8b55-6e2843001075")]
            public virtual RepoItemInfo RcmloginuserInfo
            {
                get
                {
                    return _rcmloginuserInfo;
                }
            }

            /// <summary>
            /// The Welcome item.
            /// </summary>
            [RepositoryItem("925a003a-60ec-481d-803d-074fe0faeffc")]
            public virtual Ranorex.DivTag Welcome
            {
                get
                {
                    return _welcomeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Welcome item info.
            /// </summary>
            [RepositoryItemInfo("925a003a-60ec-481d-803d-074fe0faeffc")]
            public virtual RepoItemInfo WelcomeInfo
            {
                get
                {
                    return _welcomeInfo;
                }
            }

            /// <summary>
            /// The Minmodetoggle item.
            /// </summary>
            [RepositoryItem("716da320-4020-4115-9937-a68be52b36bf")]
            public virtual Ranorex.SpanTag Minmodetoggle
            {
                get
                {
                    return _minmodetoggleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Minmodetoggle item info.
            /// </summary>
            [RepositoryItemInfo("716da320-4020-4115-9937-a68be52b36bf")]
            public virtual RepoItemInfo MinmodetoggleInfo
            {
                get
                {
                    return _minmodetoggleInfo;
                }
            }

            /// <summary>
            /// The AdiagneAtzenityFr item.
            /// </summary>
            [RepositoryItem("c9e65b8b-f806-46c4-af3c-19b296961954")]
            public virtual Ranorex.SpanTag AdiagneAtzenityFr
            {
                get
                {
                    return _adiagneatzenityfrInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AdiagneAtzenityFr item info.
            /// </summary>
            [RepositoryItemInfo("c9e65b8b-f806-46c4-af3c-19b296961954")]
            public virtual RepoItemInfo AdiagneAtzenityFrInfo
            {
                get
                {
                    return _adiagneatzenityfrInfo;
                }
            }

            /// <summary>
            /// The Rcmbtn101 item.
            /// </summary>
            [RepositoryItem("b904b428-fe46-4fc7-807b-7b84c94065e6")]
            public virtual Ranorex.ATag Rcmbtn101
            {
                get
                {
                    return _rcmbtn101Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Rcmbtn101 item info.
            /// </summary>
            [RepositoryItemInfo("b904b428-fe46-4fc7-807b-7b84c94065e6")]
            public virtual RepoItemInfo Rcmbtn101Info
            {
                get
                {
                    return _rcmbtn101Info;
                }
            }
        }

        /// <summary>
        /// The MessagerieViaducBienvenueSurMessa1AppFolder folder.
        /// </summary>
        [RepositoryFolder("2e4806e2-656f-43af-acf3-27b971ed5819")]
        public partial class MessagerieViaducBienvenueSurMessa1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pagetablistInfo;
            RepoItemInfo _element192300696Info;

            /// <summary>
            /// Creates a new MessagerieViaducBienvenueSurMessa1  folder.
            /// </summary>
            public MessagerieViaducBienvenueSurMessa1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessagerieViaducBienvenueSurMessa1", "/form[@title~'^Messagerie\\ Viaduc\\ ::\\ Bien']", parentFolder, 30000, null, true, "2e4806e2-656f-43af-acf3-27b971ed5819", "")
            {
                _pagetablistInfo = new RepoItemInfo(this, "PageTabList", "container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']", 30000, null, "8fdff356-6d8e-4ef6-a7a4-2fc778bb3b80");
                _element192300696Info = new RepoItemInfo(this, "Element192300696", "element[@controlid='192300696']", 30000, null, "d06541f5-45ea-4b2e-9885-f89e609afaaa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e4806e2-656f-43af-acf3-27b971ed5819")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e4806e2-656f-43af-acf3-27b971ed5819")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PageTabList item.
            /// </summary>
            [RepositoryItem("8fdff356-6d8e-4ef6-a7a4-2fc778bb3b80")]
            public virtual Ranorex.TabPageList PageTabList
            {
                get
                {
                    return _pagetablistInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The PageTabList item info.
            /// </summary>
            [RepositoryItemInfo("8fdff356-6d8e-4ef6-a7a4-2fc778bb3b80")]
            public virtual RepoItemInfo PageTabListInfo
            {
                get
                {
                    return _pagetablistInfo;
                }
            }

            /// <summary>
            /// The Element192300696 item.
            /// </summary>
            [RepositoryItem("d06541f5-45ea-4b2e-9885-f89e609afaaa")]
            public virtual Ranorex.Unknown Element192300696
            {
                get
                {
                    return _element192300696Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element192300696 item info.
            /// </summary>
            [RepositoryItemInfo("d06541f5-45ea-4b2e-9885-f89e609afaaa")]
            public virtual RepoItemInfo Element192300696Info
            {
                get
                {
                    return _element192300696Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("1db093ea-491a-4527-a793-62d73858c325")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _messagerieviaducbienvenuesurmessaInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "1db093ea-491a-4527-a793-62d73858c325", "")
            {
                _messagerieviaducbienvenuesurmessaInfo = new RepoItemInfo(this, "MessagerieViaducBienvenueSurMessa", "container[@controlid='40965']//toolbar[@accessiblename~'^Applications\\ en\\ cours\\ d’e']/button[@accessiblename~'^Messagerie\\ Viaduc\\ ::\\ Bien']", 30000, null, "9660c1ac-b26d-4bea-81ab-25372f7c67a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1db093ea-491a-4527-a793-62d73858c325")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1db093ea-491a-4527-a793-62d73858c325")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MessagerieViaducBienvenueSurMessa item.
            /// </summary>
            [RepositoryItem("9660c1ac-b26d-4bea-81ab-25372f7c67a1")]
            public virtual Ranorex.Button MessagerieViaducBienvenueSurMessa
            {
                get
                {
                    return _messagerieviaducbienvenuesurmessaInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MessagerieViaducBienvenueSurMessa item info.
            /// </summary>
            [RepositoryItemInfo("9660c1ac-b26d-4bea-81ab-25372f7c67a1")]
            public virtual RepoItemInfo MessagerieViaducBienvenueSurMessaInfo
            {
                get
                {
                    return _messagerieviaducbienvenuesurmessaInfo;
                }
            }
        }

        /// <summary>
        /// The MessagerieViaducMessagesRecusGoAppFolder folder.
        /// </summary>
        [RepositoryFolder("803053fd-cd02-440e-9b53-4ea3d95b4d14")]
        public partial class MessagerieViaducMessagesRecusGoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechromeInfo;

            /// <summary>
            /// Creates a new MessagerieViaducMessagesRecusGo  folder.
            /// </summary>
            public MessagerieViaducMessagesRecusGoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessagerieViaducMessagesRecusGo", "/form[@title~'^Messagerie\\ Viaduc\\ ::\\ Mess']", parentFolder, 30000, null, true, "803053fd-cd02-440e-9b53-4ea3d95b4d14", "")
            {
                _googlechromeInfo = new RepoItemInfo(this, "GoogleChrome", "container[@accessiblename=$PageMail]", 30000, null, "a19795b8-83b9-4a4d-a520-7ecba077dd72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("803053fd-cd02-440e-9b53-4ea3d95b4d14")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("803053fd-cd02-440e-9b53-4ea3d95b4d14")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome item.
            /// </summary>
            [RepositoryItem("a19795b8-83b9-4a4d-a520-7ecba077dd72")]
            public virtual Ranorex.Container GoogleChrome
            {
                get
                {
                    return _googlechromeInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("a19795b8-83b9-4a4d-a520-7ecba077dd72")]
            public virtual RepoItemInfo GoogleChromeInfo
            {
                get
                {
                    return _googlechromeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}