///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TeqtRano
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestEmail recording.
    /// </summary>
    [TestModule("b77b48b5-080e-449a-9e5d-92b09f80a131", ModuleType.Recording, 1)]
    public partial class TestEmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TeqtRanoRepository repository.
        /// </summary>
        public static TeqtRanoRepository repo = TeqtRanoRepository.Instance;

        static TestEmail instance = new TestEmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestEmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestEmail Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable PageMail.
        /// </summary>
        [TestVariable("0896eab2-cc72-4288-97ec-711d7b375f1c")]
        public string PageMail
        {
            get { return repo.PageMail; }
            set { repo.PageMail = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa.Submit' at 69;14.", repo.MessagerieViaducBienvenueSurMessa.SubmitInfo, new RecordItemIndex(0));
            repo.MessagerieViaducBienvenueSurMessa.Submit.Click("69;14");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessagerieViaducBienvenueSurMessa.Minmodetoggle' at 9;24.", repo.MessagerieViaducBienvenueSurMessa.MinmodetoggleInfo, new RecordItemIndex(1));
            //repo.MessagerieViaducBienvenueSurMessa.Minmodetoggle.Click("9;24");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFr'.", repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, "TagName", "span");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFr'.", repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, new RecordItemIndex(3));
            //Validate.Attribute(repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, "Visible", "True");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='username') on item 'MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFr'.", repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, new RecordItemIndex(4));
            //Validate.Attribute(repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, "Class", "username");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='adiagne@zenity.fr') on item 'MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFr'.", repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, new RecordItemIndex(5));
            //Validate.Attribute(repo.MessagerieViaducBienvenueSurMessa.AdiagneAtzenityFrInfo, "InnerText", "adiagne@zenity.fr");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MessagerieViaducMessagesRecusGo.GoogleChrome'.", repo.MessagerieViaducMessagesRecusGo.GoogleChromeInfo, new RecordItemIndex(6));
            Validate.Exists(repo.MessagerieViaducMessagesRecusGo.GoogleChromeInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
